<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\ElectorData;
use Faker\Generator as Faker;

$factory->define(ElectorData::class, function (Faker $faker) {
    return [
        'pd_e' => $faker->word,
        'Do_Not_Contact' => $faker->word,
        'Do_Not_Process' => $faker->word,
        'PDCode' => $faker->word,
        'E_Number' => $faker->word,
        'Forename' => $faker->word,
        'Surname' => $faker->word,
        'Housename' => $faker->word,
        'Address1' => $faker->word,
        'StreetArea' => $faker->word,
        'Town' => $faker->word,
        'County' => $faker->word,
        'Postcode' => $faker->word,
        'Telephone' => $faker->word,
        'Email' => $faker->word,
        'Mobile' => $faker->word,
        'Gender' => $faker->word,
        'Constitutional_Preference' => $faker->word,
        'Strength_of_Support' => $faker->word,
        'Party_LPC' => $faker->word,
        'Consider_Plaid' => $faker->word,
        'ByElection_Vote19' => $faker->word,
        'Vote19' => $faker->word,
        'ByElection_Vote18' => $faker->word,
        'Vote18' => $faker->word,
        'byelection_Vote17' => $faker->word,
        'westminster_Vote17' => $faker->word,
        'Vote17' => $faker->word,
        'byelection_Vote16' => $faker->word,
        'Vote16' => $faker->word,
        'EURef_Vote16' => $faker->word,
        'byelection_Vote15' => $faker->word,
        'Vote15' => $faker->word,
        'ByElection_Vote14' => $faker->word,
        'Vote14' => $faker->word,
        'ByElection_Vote13' => $faker->word,
        'Vote13' => $faker->word,
        'ByElection_Vote12' => $faker->word,
        'Vote12' => $faker->word,
        'Vote11' => $faker->word,
        'Vote_11' => $faker->word,
        'Referendum11' => $faker->word,
        'Declaration_Signed' => $faker->word,
        'Voted_in_ByElection_2019' => $faker->word,
        'Voted_in_2019' => $faker->word,
        'Voted_in_ByElection_2018' => $faker->word,
        'Voted_in_2018' => $faker->word,
        'Voted_in_byelection_2017' => $faker->word,
        'Voted_in_westminster_2017' => $faker->word,
        'Voted_in_2017' => $faker->word,
        'Voted_in_byelection_2016' => $faker->word,
        'Voted_in_2016' => $faker->word,
        'Voted_in_EURef_2016' => $faker->word,
        'Voted_in_byelection_2015' => $faker->word,
        'Voted_in_2015' => $faker->word,
        'Voted_in_ByElection_2014' => $faker->word,
        'Voted_in_2014' => $faker->word,
        'Voted_In_ByElection_2013' => $faker->word,
        'Voted_in_2013' => $faker->word,
        'Voted_in_ByElection_2012' => $faker->word,
        'Voted_in_2012' => $faker->word,
        'Voted_in_2011' => $faker->word,
        'Voted_in_2010' => $faker->word,
        'Voted_in_Ref_2011' => $faker->word,
        'Attainer_DOB' => $faker->word,
        'Interests_Held' => $faker->word,
        'Occupation' => $faker->word,
        'Welsh_Speaker' => $faker->word,
        'Postal_Vote' => $faker->word,
        'Comments' => $faker->word,
        'Entitlement' => $faker->word,
    ];
});
